### ISSUE TITLE
Isolar acesso ao entityManager no CursoController

### ISSUE THREAD

**Issue by alessandrofeitoza** [digitalcollege-classes/php-oo#14]
## O que
Atualmente o acesso a Classe EntityManager (Conexao) precisa ser inserida atraves de um "require", isso deixa o código bem repetitivo.

Precisamos isolar esse acesso e centralizar para respeitar o padrão DRY

**Comment by alessandrofeitoza** [comment]
Author : @JacoGois

**Comment by JacoGois** [comment]
https://github.com/digitalcollege-classes/php-oo/pull/17 CR @alessandrofeitoza

**Comment by alessandrofeitoza** [comment]
Closed by #17
